id: A1974E0CC
title: The Swift Accomplishment of Enlightened Activity through Invocation and Offering
type: translation
pechas:
- I951D68AF
- I44A5CA3C
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:05.540809
  last_modified_at: 2023-01-04 13:08:05.540821
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I951D68AF/6216: '4526'
  I44A5CA3C/2978: '4526'
